### ISSUE TITLE
Automate publishing to NuGet

### ISSUE THREAD

**Issue by jdhmtl** [wayfair-incubator/wayfair-text-json#11]
## Problem Statement

This package is not yet available through NuGet. That's going to be a barrier to adoption.

## Proposed Solution

Implement a CI solution through GitHub Actions that will package and publish to NuGet. Ideally, this will be configured such that preview and beta versions can be published, as well as releases when merging into `main`.

**Comment by wbaldoumas** [comment]
This is completed. Documentation on publishing to NuGet can be found [here](https://github.com/wayfair-incubator/wayfair-text-json/blob/main/RELEASING.md).
